### ISSUE TITLE
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'admin_user' for key 'username'")

### ISSUE THREAD

**Issue by yvan-sraka** [cppccn/server#50]
``` shell
Creating Super User for Cappuccino-App ...
Password: 
Password (again): 
Traceback (most recent call last):
  File "/home/yvan/cappuccino-server/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/yvan/cappuccino-server/env/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/home/yvan/cappuccino-server/env/lib/python3.5/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/home/yvan/cappuccino-server/env/lib/python3.5/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/home/yvan/cappuccino-server/env/lib/python3.5/site-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/home/yvan/cappuccino-server/env/lib/python3.5/site-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/home/yvan/cappuccino-server/env/lib/python3.5/site-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/home/yvan/cappuccino-server/env/lib/python3.5/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'admin_user' for key 'username'")
```

**Comment by MattiaPrimavera** [comment]
That comes from the fact `install.sh` creates a django super user which is probably stored inside the `mysql database`, that's why when you run the install a second time, we got a `duplicate entry error`.

How do we fix that? Couldn't it be risky to previously delete those already existing values in the `mysql database`?

**Comment by yvan-sraka** [comment]
This issue is no longer relevant.
